In [1]:
import numpy as np
import time

In [ ]:
arr1 = np.array(
    [1,2,3]
)
arr

In [3]:
print(arr1)

[1 2 3]


In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1[0]

np.int64(1)

In [11]:
arr2 = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

In [15]:
arr2[1][2]

np.int64(6)

In [18]:
arr_3 = np.array(
    [
        1,2,3, "hello"
    ]
)
arr_3

array(['1', '2', '3', 'hello'], dtype='<U21')

In [20]:
type(arr_3[1])

numpy.str_

In [21]:
arr_4 = np.array(
    [1,2,3], dtype =np.int8
)
arr_4

array([1, 2, 3], dtype=int8)

In [22]:
list(range(1,11,2))

[1, 3, 5, 7, 9]

In [26]:
b = np.arange(1,11,2)
b

array([1, 3, 5, 7, 9])

In [28]:
np_Linspace_1 = np.linspace(1,100,10)
print(np_Linspace_1)

[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [ ]:
for num in np.linspace(1,10,10, dtype = np.int8):
    print(num)

1
2
3
4
5
6
7
8
9
10


In [42]:
npz_1 = np.ones(5)
print(npz_1.ndim)
npz_1

1


array([1., 1., 1., 1., 1.])

In [43]:
npz_2 = np.ones((5,5,5), dtype = np.int8)
npz_2.ndim

3

In [44]:
npz_2

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int8)

In [ ]:
[
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]
]

In [45]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
[
    [10, 10, 10],
    [10, 10, 10]
]

In [49]:
np.eye(7,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [50]:
np.empty((2,2))

array([[  1.,  34.],
       [ 67., 100.]])

In [53]:
np.random.rand(3,1)

array([[0.29769526],
       [0.62113379],
       [0.26239019]])

In [ ]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)

print(arr[0])  # 1D 
print(arr[1])  # 1D

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array(
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

arr.shape (3, 3)

(3, 3)

In [55]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr.shape

(2, 3)

In [63]:
arr = np.array(
    [
        [1,2,3],
        [4,5,6]
    ]
)
arr 

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr.shape

(2, 3)

In [65]:
arr.ndim

2

In [66]:
arr.size

6

In [67]:
arr.dtype

dtype('int64')

In [69]:
arr.itemsize

8

In [68]:
arr.nbytes

48

In [70]:
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])